---
title: "References for economic analysis of Columbia River salmon"
author: "Mark Scheuerell"
output:
  html_document:
    theme: readable
    highlight: textmate
    toc: true
    toc_float: true
    toc_depth: 3
bibliography: "mark_references.bib"
csl: "ecology.csl"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
```

# Load `{knitcitations}` package

```{r load_knitcitations}
## load the package
library("knitcitations")

## clean out any existing .bib files
cleanbib()

## set pandoc for formatting
options("citation_format" = "pandoc")
```

## Cite by DOI

You can cite an article by its DOI, using either `citep()` or `citet()`, and the full citation information will be gathered automatically. For example, the inline command

```{r}
citep("10.1890/11-0011.1")
```

On the other hand, the inline command

```{r}
citet("10.1098/rspb.2013.1372")
```


## Citations



## References

```{r, echo = FALSE, message = FALSE}
## create ref cited section
write.bibtex(file = "mark_references.bib")
```

